### ISSUE TITLE
[Bug] FOC with Regions Unexplored

### ISSUE THREAD

**Issue by miniBill** [Stardust-Labs-MC/Terralith#67] opened 2023-11-24 19:34 UTC
### What Minecraft version(s) does this apply to?

1.19.x

### Project version

2.3.12

### Mod or datapack version?

Mod (Forge)

### Describe the bug

Basically the same issue as https://github.com/Stardust-Labs-MC/Terralith/issues/57, but for jungle instead of sparse_jungle.

### Additional context

```
Caused by: java.lang.IllegalStateException: Feature order cycle found, involved sources: [Reference{ResourceKey[minecraft:worldgen/biome / minecraft:jungle]=net.minecraft.world.level.biome.Biome@60337cbd}, Reference{ResourceKey[minecraft:worldgen/biome / regions_unexplored:sparse_rainforest]=net.minecraft.world.level.biome.Biome@63daa3da}]
```

**Comment by catter1** [comment] 2023-11-24 20:01
Please add the [Cyanide](https://www.curseforge.com/minecraft/mc-mods/cyanide-forge) mod to your loadout, create a world again, let it crash, and send the *entire* crash log

**Comment by miniBill** [comment] 2023-11-24 20:54
I'm guessing you want:
```
Caused by: com.alcatrazescapee.cyanide.codec.FeatureCycleDetector$FeatureCycleException: A feature cycle was found.
Cycle:
At step 9
Feature 'minecraft:patch_melon_sparse'
  must be before 'minecraft:vines' (defined in 'wythers:jungle_canyon' at index 7, 8 and 8 others)
  must be before 'minecraft:patch_melon_sparse' (defined in 'regions_unexplored:eucalyptus_forest' at index 6, 7 and 1 others)
  ```
  
  If needed I can attach the whole log, but it's like 6k lines :D

**Comment by miniBill** [comment] 2023-11-24 20:55
Ooooh. Is the issue an incompatibility between wythers and regions unexplored?

Edit: it does not crash if I disable wythers. Guess I'll have to report there?

**Comment by catter1** [comment] 2023-11-24 21:52
Next time, please send the entire log. Often times it is very helpful to see other things other than just the main error, such as which versions of mods, other mods being used (even if not in the error), and previous non-fatal errors that may have occured during startup. Context matters!

But I did find the issue: it is indeed with WWOO. I just made [a report](https://github.com/Cristelknight999/Expanded-Ecosphere/issues/74) with them, which I did not realize was a duplicate of https://github.com/Cristelknight999/Expanded-Ecosphere/issues/66 until after the fact. This has been left open for a month, and Regions Unexplored is also already aware of this issue. Just have to wait for WWOO to fix it.

**Closed as completed by catter1** 2023-11-24 21:52 UTC
Labels: bug

**Comment by miniBill** [comment] 2023-11-24 23:34
Thank you very much for your patience!

Next time I'll make sure to paste the whole log :)
