### ISSUE TITLE
Superflat

### ISSUE THREAD

**Issue by Shadowbee27** [Stardust-Labs-MC/Terralith#148] opened 2024-07-26 09:45 UTC
### What Minecraft version(s) does this apply to?

1.20

### Project version

2.5.1

### Mod or datapack version?

Mod (Fabric)

### Describe the bug

If you gennerate a superflat world it gennerats a normal one

**Comment by catter1** [comment] 2024-07-26 11:26
Duplicate of #113

**Closed as not planned** 2024-07-26 11:27 UTC
Labels: wontfix
