### ISSUE TITLE
[Bug] Some Console Errors

### ISSUE THREAD

**Issue by frosthuuuund** [Stardust-Labs-MC/Terralith#138] opened 2024-07-03 18:43 UTC
### What Minecraft version(s) does this apply to?

1.20

### Project version

2.5.3

### Mod or datapack version?

Datapack

### Describe the bug

```
[18:39:39] [Worker-Main-15/ERROR]: Couldn't load tag biome_tag_villagers:villager_snowy as it is missing following references: terralith:reference/temperature/frozen_all (from file/Terralith_1.21_v2.5.3.zip)
[18:39:39] [Worker-Main-15/ERROR]: Couldn't load tag biome_tag_villagers:villager_taiga as it is missing following references: terralith:reference/taiga (from file/Terralith_1.21_v2.5.3.zip)
[18:39:39] [Worker-Main-15/ERROR]: Couldn't load tag biome_tag_villagers:villager_desert as it is missing following references: terralith:reference/desert_all (from file/Terralith_1.21_v2.5.3.zip)
[18:39:39] [Worker-Main-15/ERROR]: Couldn't load tag biome_tag_villagers:villager_savanna as it is missing following references: terralith:reference/savanna (from file/Terralith_1.21_v2.5.3.zip)
[18:39:39] [Worker-Main-15/ERROR]: Couldn't load tag biome_tag_villagers:villager_jungle as it is missing following references: terralith:reference/jungle (from file/Terralith_1.21_v2.5.3.zip)
[18:39:39] [Worker-Main-15/ERROR]: Couldn't load tag biome_tag_villagers:villager_swamp as it is missing following references: terralith:reference/swamp (from file/Terralith_1.21_v2.5.3.zip)

```

**Comment by catter1** [comment] 2024-07-03 21:13
Duplicate of #121

**Closed as not planned by catter1** 2024-07-03 21:13 UTC
Labels: bug, duplicate
